# Generated by Django 4.2.2 on 2023-07-01 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sensor_id', models.IntegerField()),
                ('min_range', models.FloatField(default=0)),
                ('max_range', models.FloatField(default=100)),
            ],
        ),
    ]
