# Generated by Django 4.2.2 on 2023-07-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='Sensor_id',
        ),
        migrations.AddField(
            model_name='sensor',
            name='name',
            field=models.CharField(max_length=25, null=True, unique=True),
        ),
    ]
