# Generated by Django 4.2.2 on 2023-07-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aqapp', '0002_remove_sensor_sensor_id_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='pollutant',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
