# Generated by Django 4.2.2 on 2023-07-01 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aqapp', '0003_sensor_pollutant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pollutant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('value', models.FloatField(null=True)),
                ('pollutant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqapp.pollutant')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aqapp.sensor')),
            ],
        ),
        migrations.AlterField(
            model_name='sensor',
            name='pollutant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='aqapp.pollutant'),
        ),
    ]
